# Source language and JDK version to use
language: java
jdk: oraclejdk7

# Compile and package JAR and set build properties
install: ./gradlew build -PbuildNumber=$TRAVIS_BUILD_NUMBER -PciSystem=travis -Pcommit=${TRAVIS_COMMIT:0:7}

# Perform steps after compilation/test success
after_success:
  # Generate Cobertura report for Coveralls.io
  - "./gradlew cobertura coveralls -PserviceJobId=$TRAVIS_JOB_ID"
  # Check if commit s not a pull request, if git repo is official, and if branch is master. If checks pass, add libs and deploy artifacts to Maven repository.
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == InspireNXE/Pulse ]] && [[ $TRAVIS_BRANCH == master ]] && ./gradlew build shadowJar uploadArchives"

# Notification services
notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  webhooks:
    # Send build information and status to Notifico
    - http://n.tkte.ch/h/1954/GVanmDazB-fPCVDSizOPGH3B

# Environmental system variables
env:
  global:
    # Make the log output cleaner
    - TERM=dumb
    # Secure environment variables
    - secure: "SZXibF7/zyZRu5sxROc+K6sTwiwyHuvZUV7FhMcZ8x53mfoBemwd1Wd7vaSw6tFU4umn1holGib9VNGhpSpQTMn0EusnlKVcr8Tl8J1k09iDwrJdKIdCBmjEM3cytujkwIi8Eowf0T9LMTLRG/odtB+0vdSSznuIbMfI/d2PXrY="
    - secure: "VDTGMFNXQSFe62PI8D6jYOQ2YHdgTVutmazSCDgUw2uA0m79m9LbO4vUwDvSmBZr758GnfXKJI6X8P9OqOckj1A3p7mizfyqynPWVvpn5WhM+2jmiM0br7yw6Rsy/tarxwjKeBkr4LLwHhDoq53KZaulgr/DTeVaVFDj36tICzE="
